run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # Enabled by default, see https://golangci-lint.run/usage/linters#enabled-by-default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Enabled by coraza
    - goimports
    - gofmt
    - gocritic
