version: "2"
timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - errname
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports


    # - depguard
    # - errname
    # - errorlint
    # - goconst
    # - gocritic
    # - lll
    # - misspell
    # - prealloc
    # - revive
    # - unconvert
    # - usetesting
