run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # Enabled by default, see https://golangci-lint.run/usage/linters#enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt
    - gocritic
issues:
  exclude-rules:
    - path: magefile\.go
      linters:
        - deadcode
    - path: internal\/corazawaf\/rule\.go
      linters:
        - staticcheck
