#!/bin/bash
id -u coraza-waf &>/dev/null || useradd -r -s /bin/false coraza-waf
chown -R coraza-waf:root /opt/coraza-waf/log
chown -R root:root /etc/coraza-waf
find /opt/coraza-waf -type d -exec chmod 755 {} \;
find /etc/coraza-waf -type d -exec chmod 755 {} \;
find /etc/coraza-waf -type f -exec chmod 655 {} \;
chown -R root:root /bin/coraza-waf
chown -R root:root /bin/eskip
update-rc.d coraza-waf defaults
ldconfig
#TODO add inittab for autorespawn