// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package transformations

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations(in *jlexer.Lexer, out *tests) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(tests, 0, 0)
			} else {
				*out = tests{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 test
			(v1).UnmarshalTinyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations(out *jwriter.Writer, in tests) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalTinyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v tests) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v tests) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tests) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *tests) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations(l, v)
}
func tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations1(in *jlexer.Lexer, out *test) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "input":
			out.Input = string(in.String())
		case "output":
			out.Output = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "ret":
			out.Ret = int(in.Int())
		case "type":
			out.Type = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations1(out *jwriter.Writer, in test) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"input\":"
		out.RawString(prefix[1:])
		out.String(string(in.Input))
	}
	{
		const prefix string = ",\"output\":"
		out.RawString(prefix)
		out.String(string(in.Output))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"ret\":"
		out.RawString(prefix)
		out.Int(int(in.Ret))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v test) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v test) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson39df0d36EncodeGithubComCorazawafCorazaV3Transformations1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *test) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *test) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson39df0d36DecodeGithubComCorazawafCorazaV3Transformations1(l, v)
}
