Include @coraza.conf-recommended
SecAuditEngine RelevantOnly
SecAuditLog /dev/stdout
SecAuditLogFormat JSON

SecDefaultAction "phase:3,log,auditlog,pass"
SecDefaultAction "phase:4,log,auditlog,pass"
SecDefaultAction "phase:5,log,auditlog,pass"
# CRS inclusion
Include @crs-setup.conf.example
Include @owasp_crs/*.conf

# Enable the WAF in blocking mode
# Example request match: curl -i 'localhost:8090/hello?file=../etc/passwd'
SecRuleEngine On
SecRequestBodyAccess On

# Custom example rules
# Matches curl -i 'localhost:8090/hello?id=0'
SecRule ARGS:id "@eq 0" "id:100,phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
SecRule REQUEST_BODY "@contains password" "id:101,phase:2,deny,status:403,msg:'Invalid request body',log,auditlog"
