---
testoverride:
  ignore:
    # TODO(anuraaga): Examine the cause of failure and whether it is expected or should be fixed.
    920100-4: ''
    920100-5: ''
    920100-8: ''
    920170-3: ''
    920171-2: ''
    920171-3: ''
    920270-4: ''
    920272-5: ''
    920280-1: ''
    920290-1: ''
    920420-8: ''
    920430-5: ''
    920430-8: ''
    934120-23: 'regex matches arbitrary bytes'
    934120-24: 'regex matches arbitrary bytes'
    934120-25: 'regex matches arbitrary bytes'
    934120-26: 'regex matches arbitrary bytes'
    934120-39: 'regex matches arbitrary bytes'
    941310-1: 'regex matches arbitrary bytes'
    941310-3: 'regex matches arbitrary bytes'
    944200-1: 'regex matches arbitrary bytes'
