---
testoverride:
  ignore:
    920100-4: 'Invalid uri, Coraza not reached - 404 page not found'
    920100-5: 'Invalid uri, Coraza not reached - 404 page not found'
    920100-8: 'Go/http allows a colon in the path. Test expects status 400 or 403 (Apache behaviour)'
    920270-4: 'Rule works, log contains 920270. Test expects status 400 (Apache behaviour)'
    920272-5: 'Rule works, log contains 920272. Test expects status 400 (Apache behaviour)'
    920290-1: 'Rule works, log contains 920290. Test expects status 400 (Apache behaviour)'
    920290-4: 'Go/http returns 400 Bad Request: missing required Host header'
    920430-8: 'Go/http does not allow HTTP/3.0 - 505 HTTP Version Not Supported'
    932200-13: 'wip'
    930110-7: 'CRS issue: https://github.com/coreruleset/coreruleset/issues/3736'
