---
testoverride:
  ignore:
    920100-4: 'Invalid uri, Coraza not reached - 404 page not found'
    920100-5: 'Invalid uri, Coraza not reached - 404 page not found'
    920100-8: 'Go/http allows a colon in the path. Test expects status 400 or 403 (Apache behaviour)'
    920170-3: 'HEAD request with data. Go/http does not allow it - 400 Bad Request'
    920171-2: 'Go/http removes the Transfer-Encoding header after parsing it (https://github.com/golang/go/blob/master/src/net/http/transfer.go#L631). The test looks for it'
    920171-3: 'Go/http removes the Transfer-Encoding header after parsing it (https://github.com/golang/go/blob/master/src/net/http/transfer.go#L631). The test looks for it'
    920270-4: 'Rule works, log contains 920270. Test expects status 400 (Apache behaviour)'
    920272-5: 'Rule works, log contains 920272. Test expects status 400 (Apache behaviour)'
    920290-1: 'Rule works, log contains 920290. Test expects status 400 (Apache behaviour)'
    920420-8: 'HEAD request with data. Go/http does not allow it - 400 Bad Request'
    920430-5: 'Test has expect_error, Go/http and Envoy return 400'
    920430-8: 'Go/http does no allow HTTP/3.0 - 505 HTTP Version Not Supported'
