name: Fixes dependabot lint
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: v1.19.x
          cache: true
      - name: Format code
        run: go run mage.go format
      - name: Check for uncommitted changes
        id: check-uncommited
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Commit and push changes
        if: steps.check-uncommited.outputs.outcome == failure()
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: run mage format"
