name: Fixes dependabot lint
on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: v1.18.x
          cache: true
      - name: Format code
        run: go run mage.go format
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: go mod tidy"
