name: Fuzz tests

on:
  schedule:
    # https://crontab.guru/#05_14_*_*_*
    - cron: "05 14 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  fuzz:
    name: Fuzz tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ">=1.25.0"
      - run: go run mage.go fuzz
      - run: |
          gh issue create --title "$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER failed" \
                          --body "See [$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)."
        if: failure() && github.run_attempt == 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
