name: Regression Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

permissions: {}

concurrency:
  group: regression-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
        build-flag:
          - ""
          - "coraza.rule.mandatory_rule_id_check"
          - "coraza.rule.case_sensitive_args_keys"
          - "coraza.rule.no_regex_multiline"
          - "coraza.no_memoize"
          - "coraza.rule.rx_prefilter"
          - "coraza.rule.multiphase_evaluation"
          - "no_fs_access"
          - "coraza.rule.multiphase_evaluation,coraza.rule.mandatory_rule_id_check"
          - "coraza.rule.multiphase_evaluation,coraza.rule.case_sensitive_args_keys"
          - "coraza.rule.multiphase_evaluation,coraza.rule.no_regex_multiline"
          - "no_fs_access,coraza.no_memoize"
          - "coraza.rule.mandatory_rule_id_check,coraza.rule.case_sensitive_args_keys,coraza.rule.no_regex_multiline"
          - "coraza.rule.multiphase_evaluation,coraza.rule.mandatory_rule_id_check,coraza.rule.case_sensitive_args_keys,coraza.rule.no_regex_multiline,coraza.no_memoize,no_fs_access,coraza.rule.rx_prefilter"
        include:
          - go-version: 1.26.x
            os: ubuntu-latest
            build-flag: ""
          - go-version: 1.26.x
            os: ubuntu-latest
            build-flag: "coraza.rule.multiphase_evaluation,coraza.rule.mandatory_rule_id_check,coraza.rule.case_sensitive_args_keys,coraza.rule.no_regex_multiline,coraza.no_memoize,no_fs_access"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      GOLANG_BASE_VERSION: "1.25.x"
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Tests and coverage
        env:
          BUILD_TAGS: ${{ matrix.build-flag }}
        run: go run mage.go coverage
      - name: "Codecov: General"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        if: ${{ matrix.go-version == env.GOLANG_BASE_VERSION }}
        with:
          files: build/coverage.txt
          flags: default,${{ matrix.build-flag }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Codecov: Examples"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        if: ${{ matrix.go-version == env.GOLANG_BASE_VERSION }}
        with:
          files: build/coverage-examples.txt
          flags: examples+${{ matrix.build-flag }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Codecov: FTW"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        if: ${{ matrix.go-version == env.GOLANG_BASE_VERSION }}
        with:
          files: build/coverage-ftw.txt
          flags: ftw,${{ matrix.build-flag }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Codecov: Tinygo"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        # only if coverage-tinygo.txt exists
        if: ${{ matrix.go-version == env.GOLANG_BASE_VERSION && hashFiles('build/coverage-tinygo.txt') != '' }}
        with:
          files: build/coverage-tinygo.txt
          flags: tinygo,${{ matrix.build-flag }}
          token: ${{ secrets.CODECOV_TOKEN }}
